# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        evidence.storage:
            adapter: 'WGG\Flysystem\Doctrine\DoctrineDBALAdapter'
            options:
                directory: '/evidence'
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
