kreyu_data_table:
  defaults:
    themes:
      - '@KreyuDataTable/themes/bootstrap_5.html.twig'
      - 'data_table/theme.html.twig'
    sorting:
      persistence_enabled: true
    filtration:
      persistence_enabled: true
    pagination:
      persistence_enabled: true
