vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        evidence:
            uri_prefix: /evidence
            upload_destination: evidence.storage
            delete_on_remove: false
            delete_on_update: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # Disabled as files got saved in a different directory than was eventually added to the entity
            #directory_namer: app.namer.award_directory_namer
