<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * This class represents a Flysystem file and is used for Doctrine to generate the table schema.
 */
#[ORM\Entity]
#[ORM\Table(name: 'flysystem_files')]
#[ORM\UniqueConstraint(name: 'path_unique', columns: ['path'])]
class FlysystemFile
{
    #[ORM\Id]
    #[ORM\Column(type: Types::BIGINT, columnDefinition: 'BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL')]
    private int $id;

    #[ORM\Column()]
    private string $path;

    #[ORM\Column(length: 4, options: [
        'check' => '(type = "dir" OR type = "file")'
    ])]
    private string $type;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private string $contents;

    #[ORM\Column(options: ['default' => 0])]
    private int $size = 0;

    #[ORM\Column()]
    private int $level;

    #[ORM\Column(name: 'mimetype', length: 127, nullable: true)]
    private string $mimeType;

    #[ORM\Column(length: 7, options: ['default' => 'public', 'check' => '(visibility = "public" OR visibility = "private")'])]
    private string $visibility;

    #[ORM\Column(options: ['default' => 0])]
    private int $timestamp;
}
