<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240419220113 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
        CREATE TABLE flysystem_files (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            path VARCHAR(255) NOT NULL,
            type VARCHAR(4) NOT NULL,
            contents BYTEA DEFAULT NULL,
            size INT DEFAULT 0 NOT NULL,
            level INT NOT NULL,
            mimetype VARCHAR(127) DEFAULT NULL,
            visibility VARCHAR(7) DEFAULT 'public' NOT NULL,
            timestamp INT DEFAULT 0 NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT type_check CHECK (type = 'dir' OR type = 'file'),
            CONSTRAINT visibility_check CHECK (visibility = 'public' OR visibility = 'private')
        )
        ");
        $this->addSql('CREATE UNIQUE INDEX path_unique ON flysystem_files (path)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE flysystem_files');
    }
}
